# Generated by Django 3.2.25 on 2024-09-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20240920_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_required',
            new_name='login_require',
        ),
    ]
